<?php
/*
 * (c) 2026: 975L <contact@975l.com>
 * (c) 2026: Laurent Marquet <laurent.marquet@laposte.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */
namespace c975L\SiteBundle\Service;

use c975L\ConfigBundle\Service\ConfigServiceInterface;
use c975L\UiBundle\Contract\BundleStylesheetProviderInterface;

class StylesheetProvider implements BundleStylesheetProviderInterface
{
    public function __construct(
        private readonly ConfigServiceInterface $configService,
    ) {
    }

    public function getStylesheets(): array
    {
        $stylesheets = [
            'bundles/c975lsite/css/styles.min.css',
            // Generated by ThemeVariablesCssListener from the admin-editable "theme" group configs -
            // must come after styles.min.css so its custom properties win the cascade
            'bundles/build/site-theme.css',
        ];

        // "Shape" stylesheet of the active page template (radii/shadows/fonts, see
        // sass/page-templates/*), set by ThemeCrudController::applyPreset() - loaded after
        // site-theme.css so it can override the design tokens defined there
        $stylesheet = $this->configService->get('theme-stylesheet');
        if (null !== $stylesheet && '' !== $stylesheet) {
            $stylesheets[] = 'bundles/c975lsite/css/page-templates/' . $stylesheet . '.min.css';
        }

        return $stylesheets;
    }
}
