services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\SiteBundle\Command\:
        resource: '../../Command/*'

    c975L\SiteBundle\Controller\:
        resource: '../../Controller/*'

    c975L\SiteBundle\Security\:
        resource: '../../Security/*'
