services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\SiteBundle\Command\:
        resource: '../src/Command/*'

    c975L\SiteBundle\Controller\:
        resource: '../src/Controller/*'

    c975L\SiteBundle\Security\:
        resource: '../src/Security/*'
